const Pub=require('./../Models/user');
const Link=require('./../Models/uploadlink');
const Pub1=require('./../Models/teachingfeedback');
const fs = require('fs');
const excel = require('exceljs');
const tempfile = require('tempfile');


exports.getaddteachingfeedback= async (req,res) => {
    //res.cookie("user","Akshata");
    const user1=req.cookies['user'];
    var name="";
    res.status(200).render('addteachingfeedback', {
        title: 'Teaching Feedback',
        colid: req.params.id
    });
    
    
};

exports.createteachingfeedback= async (req,res) => {

    try{
        const user1=req.cookies['user'];
        const colid=req.cookies['colid'];
        const name=req.cookies['name'];
        const today = new Date();
        const pub1= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Interest generated by the teacher on the subject.",
            score: req.body.one,
            feedbackdate:today
            
        });
        const pub2= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Clarity of exposition of the teacher in the classroom.",
            score: req.body.two,
            feedbackdate:today
        }); 
        const pub3= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Communication skill of the teacher.",
            score: req.body.three,
            feedbackdate:today
        });
        const pub4= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Coverage of the syllabus by the teacher.",
            score: req.body.four,
            feedbackdate:today
        });
        const pub5= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Encouraging students participation in the classroom.",
            score: req.body.five,
            feedbackdate:today
        });
        const pub6= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Regularity and punctuality of the teacher in taking classes.",
            score: req.body.six,
            feedbackdate:today
        });
        const pub7= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Willingness of the teacher to clear doubts of students.",
            score: req.body.seven,
            feedbackdate:today
        });
        const pub8= await Pub1.create({
            name: name,
            user: user1,
            colid: colid,
            type: 'Teaching',
            fsname: req.body.fsname,
            email: req.body.email,
            regno: req.body.regno,
            department: req.body.department,
            sem: req.body.sem,
            year: req.body.year,
            degree: req.body.degree,
            program: req.body.program,
            course: req.body.course,
            question: "Overall experience regarding teaching skill, method and learning.",
            score: req.body.eight,
            feedbackdate:today
        });
        
        
        //res.status(200).send('Hello world for all the tours through db new router');
    //    res.status(201).json({
    //        status:'Success',
    //        data: {
    //            Category: lcat1
    //        }
    //    });
       //req.flash("success", "Category has been added successfully");
       req.flash("success", "Feedback has been added successfully for user " + req.cookies['user']);
    //    res.status(200).render('addpub', {
    //     title: 'Add publication'
    // });
    res.redirect('/addteachingfeedback/' + req.params.id);

          
    } catch(err) {
        req.flash("error", "Feedback could not be added successfully. Error " + err );
        res.redirect('/addteachinfeedback/' + req.params.id);
    }   
};

exports.getexportteachingfeedback= async (req,res) => {
    //res.cookie("user","Akshata");
  
    try{
        const user1=req.cookies['user'];
        const colid=req.cookies['colid'];
        const role=req.cookies['role'];
        if (role == 'Admin') {
        } else {
            res.redirect('/notauthorized');
        }
        if(user1) {
            const lcat1233= await Pub1.find()
            .where('colid')
            .equals(colid)
            .where('feedbackdate')
            .gte(req.body.ldate)
            .where('feedbackdate')
            .lte(req.body.gdate);
            //res.status(200).send('Hello world for all the tours through db new router');
            let workbook = new excel.Workbook(); //creating workbook
	let worksheet = workbook.addWorksheet('Feedback Data'); //creating worksheet
	
	//  WorkSheet Header
	worksheet.columns = [
		{ header: 'Student Name', key: 'fsname', width: 30},
		{ header: 'Email', key: 'email', width: 30 },
		{ header: 'Registration No.', key: 'regno', width: 30},
        { header: 'Department', key: 'department', width: 30},
        { header: 'Year-Semester-Section', key: 'sem', width: 30},
        { header: 'Year', key: 'year', width: 30},
        { header: 'Degree', key: 'degree', width: 30},
        { header: 'Program name', key: 'program', width: 30},
        { header: 'Course name', key: 'course', width: 30},
        { header: 'Question', key: 'question', width: 30},
        { header: 'Score', key: 'score', width: 30},
        { header: 'Feedback Date', key: 'feedbackdate', width: 30}
        
		
,       

	];
	
	// Add Array Rows
	worksheet.addRows(lcat1233);

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader("Content-Disposition", "attachment; filename=feedbackdata.xlsx");


    var tempFilePath = tempfile('.xlsx');
        workbook.xlsx.writeFile(tempFilePath).then(function() {
            console.log('file is written');
            res.sendFile(tempFilePath, function(err){
                console.log('---------- error downloading file: ' + err);
            });
        });

        } else {
            req.flash("error", "You have been logged out. Please login to continue.");
            res.redirect('/login');

        }               
    } catch(err) {
        res.status(400).json({
            status:'Failed',
            message: err
        });

    }  
};
